export const dynamic = "force-static";

const BODY = String.raw`<!DOCTYPE html>

<html lang="pt-BR">
<head>
<base href="/lore/seika/"/>
<link href="https://dnd.faysk.dev/lore/seika" rel="canonical"/>
<meta content="https://dnd.faysk.dev/lore/seika" property="og:url"/>
<meta charset="utf-8"/>
<meta content="width=device-width, initial-scale=1" name="viewport"/>
<meta content="#17130f" name="theme-color"/>
<meta content="Seika — Antes do Inverno. Uma experiência narrativa sobre casa, cuidado, sorte, espíritos e a estrada que começa no verão." name="description"/>
<meta content="Seika — Antes do Inverno" property="og:title"/>
<meta content="Uma história sobre cuidado, casa e a estrada que começa quando alguém não volta." property="og:description"/>
<meta content="https://dnd.faysk.dev/lore/seika/assets/web/wide-departure-full.avif" property="og:image"/>
<title>Seika — Antes do Inverno</title>
<link href="seika-mark.svg" rel="icon" type="image/svg+xml"/>
<link as="image" fetchpriority="high" href="assets/web/wide-ink-moon.avif" rel="preload" type="image/avif"/><link href="styles.css" rel="stylesheet"/>
</head>
<body>
<a class="skip-link" href="#historia">Pular para a história</a>
<div aria-hidden="true" class="reading-progress"><span id="progressBar"></span></div>
<div aria-hidden="true" class="paper-grain"></div>
<div aria-hidden="true" class="vignette"></div>
<header class="site-chrome" id="siteChrome">
<a aria-label="Seika — voltar ao início" class="brand" href="#topo"><span aria-hidden="true" class="brand-mark">◐</span><span>SEIKA</span></a>
<button aria-controls="chapterNav" aria-expanded="false" class="menu-toggle" id="menuToggle" type="button"><span></span><span></span><span></span><span class="sr-only">Abrir capítulos</span></button>
<nav aria-label="Capítulos" class="chapter-nav" id="chapterNav"><a href="#casa">Casa</a><a href="#lucky">Lucky</a><a href="#ami">Ami</a><a href="#ren">Ren</a><a href="#primeiro-exorcismo">Primeiro exorcismo</a><a href="#ausencia">A primavera</a><a href="#partida">Partida</a><a href="#caderno">Caderno</a></nav>
</header>
<aside aria-label="Relógio da história" class="season-rail"><div aria-hidden="true" class="season-line"><i id="seasonIndicator"></i></div><div class="season-labels"><span data-season-label="memoria">memória</span><span data-season-label="primavera">primavera</span><span data-season-label="verao">verão</span><span data-season-label="inverno">inverno</span></div></aside>
<main id="historia">
<section class="hero scene-observer" data-chapter="topo" data-season="memoria" id="topo"><div aria-hidden="true" class="hero-ink parallax-layer" data-depth="0.08"><img alt="" fetchpriority="high" src="assets/web/wide-ink-moon.avif" type="image/avif"/></div><div aria-hidden="true" class="hero-haze"></div><div aria-hidden="true" class="hero-spirit-glow"></div><div class="hero-copy reveal reveal-now"><p class="eyebrow">Catfolk · Oracle · Mistério da Vida</p><h1>SEIKA</h1><p class="hero-subtitle">Antes do <em>Inverno</em></p><div class="hero-rule"><span></span><i>✦</i><span></span></div><p class="hero-thesis">Ele não se considera um aventureiro.</p><p class="hero-thesis hero-thesis-strong">Está apenas procurando um amigo.</p><a class="scroll-cta" href="#casa"><span>desenrolar a história</span><b aria-hidden="true">↓</b></a></div><div aria-hidden="true" class="hero-meta"><span>23 anos</span><span>herbalista</span><span>exorcista iniciante</span></div></section>
<section class="chapter warm scene-observer" data-chapter="casa" data-season="memoria" id="casa"><div aria-hidden="true" class="panorama panorama-village parallax-bg" data-speed="0.06"></div><div class="chapter-shade"></div><div class="story-frame story-frame-left reveal"><p class="chapter-kicker">I · Casa</p><h2>Uma vida pequena.<br/><span>Simples. Boa.</span></h2><p>Seika nasceu numa vila onde quase todos se conhecem — quem planta, quem cozinha, quem conserta ferramentas e quem esquece a mesma janela aberta antes da chuva.</p><p>Ele cresceu entre o cheiro de ervas secando, pequenos remédios, vizinhos aparecendo à porta e duas lições que acabariam seguindo com ele muito além da botica.</p><div aria-label="As duas lições de Seika" class="two-lessons"><blockquote><small>Haru</small><strong>Observe antes de tocar.</strong></blockquote><blockquote><small>Mei</small><strong>Escute antes de tratar.</strong></blockquote></div></div><div class="world-note reveal" role="note"><span>casa</span><p>O sobrenatural viria depois. Primeiro, Seika aprendeu a cuidar.</p></div></section>
<section class="chapter parchment scene-observer" data-chapter="lucky" data-season="memoria" id="lucky"><div class="section-heading reveal"><p class="chapter-kicker">II · Lucky</p><h2>Uma sorte que parecia<br/><em>boa demais.</em></h2><p class="lede">Pequenos desastres aconteciam ao redor de Seika. O estranho era como quase sempre terminavam bem.</p></div><div class="layered-scene lucky-scene" data-tilt-scene=""><div class="layered-back layered-full parallax-layer" data-depth="0.08"><img alt="Seika criança nas ruínas, diante da cobra e da pedra caída." loading="lazy" src="assets/web/wide-lucky-full.avif"/></div><div aria-hidden="true" class="scene-light"></div><div class="scene-caption reveal"><span class="memory-index">memória 01</span><h3>A pedra errou Seika.</h3><p>E esmagou a cobra que estava prestes a atacá-lo.</p></div></div><div class="lucky-ledger"><div class="luck-examples reveal"><span>perdeu-se na floresta</span><b>→</b><strong>encontrou um caminho antigo</strong><span>escorregou de uma árvore</span><b>→</b><strong>caiu sobre folhas</strong><span>seguiu a direção errada</span><b>→</b><strong>voltou com uma planta rara</strong></div><blockquote class="quote-card reveal"><p>“Sorte é só o nome que damos para alguma coisa quando ainda não entendemos por que aconteceu.”</p><cite>— Haru</cite></blockquote></div><figure class="cinematic-strip reveal" data-panorama=""><img alt="Seika criança nas ruínas, diante da cobra e da pedra caída, em composição panorâmica." loading="lazy" src="assets/web/wide-lucky-full.avif"/><figcaption><span>Lucky</span> O apelido ficou. A explicação, não.</figcaption></figure><div class="detour-note reveal"><p>Haru podia mandá-lo buscar uma erva ao norte. Horas depois, Seika voltava pelo sul, coberto de lama, com duas plantas diferentes e alguma pessoa que encontrou precisando de ajuda.</p><strong>“Seika. Vá direto.”</strong><small>Quando uma entrega era realmente urgente, a vila aprendeu a especificar.</small></div></section>
<section aria-labelledby="filosofia-titulo" class="philosophy-bridge scene-observer" data-season="memoria"><div aria-hidden="true" class="botanical-veil"></div><div class="philosophy-copy reveal"><p class="eyebrow">O método veio antes da magia</p><h2 id="filosofia-titulo">Observar. Escutar.<br/><span>Só então agir.</span></h2><p>Mais tarde, Seika levaria o mesmo princípio do herbalismo para aquilo que ervas sozinhas não conseguiam tratar.</p></div><div aria-label="Método de Seika" class="method-triad"><article class="reveal"><b>01</b><h3>Observar</h3><p>O que mudou? O que não pertence ali? O que as pessoas deixaram de perceber?</p></article><article class="reveal"><b>02</b><h3>Escutar</h3><p>Medo, espírito ou pessoa: antes de decidir, entender o que está tentando ser dito.</p></article><article class="reveal"><b>03</b><h3>Cuidar</h3><p>Nem tudo precisa ser destruído. Algumas coisas estão confusas. Algumas estão presas.</p></article></div></section>
<section class="chapter ritual scene-observer" data-chapter="ami" data-season="memoria" id="ami"><div aria-hidden="true" class="ritual-particles" id="ritualParticles"></div><div class="section-heading section-heading-light reveal"><p class="chapter-kicker">III · Ami</p><h2>O primeiro contato<br/><em>real</em> com o sobrenatural.</h2></div><div class="layered-scene ritual-scene" data-tilt-scene=""><div class="layered-back layered-full parallax-layer" data-depth="0.08"><img alt="Ritual de Ami: Seika, Ami, Ren e uma grande presença espiritual violeta." loading="lazy" src="assets/web/wide-ami-ritual-full.avif"/></div><div aria-hidden="true" class="ritual-aura"></div><div class="scene-caption scene-caption-dark reveal"><span class="memory-index">13 anos</span><h3>Outras pessoas recuaram.</h3><p>Seika não ficou porque não sentia medo. Ficou porque não conseguia aceitar deixar Ami sozinha.</p></div></div><div class="answered-moment reveal"><p>Uma parte do ritual falhou.</p><p>Seika tentou ajudar.</p><strong>E alguma coisa respondeu.</strong><small>O que exatamente aconteceu permanece sem resposta.</small></div><figure class="cinematic-strip cinematic-strip-night reveal" data-panorama=""><img alt="Ritual de Ami em panorama: Seika, Ami, Ren e uma grande presença espiritual violeta." loading="lazy" src="assets/web/wide-ami-ritual-full.avif"/><figcaption><span>O ritual de Ami</span> Ren nunca esqueceu aquele momento. Seika também não.</figcaption></figure></section>
<section class="chapter springs scene-observer" data-chapter="ren" data-season="primavera" id="ren"><div aria-hidden="true" class="spring-moon"></div><div class="section-heading reveal"><p class="chapter-kicker">IV · As primaveras de Ren</p><h2>Todo inverno ele partia.<br/><em>Toda primavera ele voltava.</em></h2><p class="lede">O que começou como gratidão à família que salvou sua vida virou tradição. Depois aprendizado. Depois amizade.</p></div><div aria-label="A relação de Seika e Ren ao longo dos anos" class="spring-timeline"><div aria-hidden="true" class="spring-line"><span></span></div><article class="spring-beat reveal"><time>13 anos</time><div><h3>Recuperação</h3><p>Haru tratou as feridas. Mei garantiu descanso. Seika fez perguntas suficientes para testar a paciência de um Tengu já ferido.</p></div></article><article class="spring-beat reveal"><time>Primavera seguinte</time><div><h3>Retorno</h3><p>Ren voltou. E então voltou de novo. A vila começou a esperar por ele como parte natural da estação.</p></div></article><article class="spring-beat reveal"><time>Anos depois</time><div><h3>Aprendizado</h3><p>Ren ensinou selos, rituais, histórias de espíritos e uma cautela que Seika frequentemente equilibrava com empatia.</p></div></article><article class="spring-beat reveal"><time>23 anos</time><div><h3>Amizade</h3><p>Quando Ren partiu naquele inverno, ninguém tratou como despedida. Ele voltaria na primavera, como sempre.</p></div></article></div></section>
<section class="chapter tavern scene-observer" data-chapter="primeiro-exorcismo" data-season="memoria" id="primeiro-exorcismo"><div class="section-heading section-heading-light reveal"><p class="chapter-kicker">V · O primeiro exorcismo</p><h2>Nem toda assombração<br/><em>quer fazer mal.</em></h2></div><div class="layered-scene exorcism-scene" data-tilt-scene=""><div class="layered-back layered-full parallax-layer" data-depth="0.08"><img alt="Primeiro exorcismo de Seika dentro da taverna, com o pequeno espírito azul." loading="lazy" src="assets/web/wide-first-exorcism-full.avif"/></div><div aria-hidden="true" class="spirit-halo"></div><div class="scene-caption scene-caption-dark reveal"><span class="memory-index">sozinho pela primeira vez</span><h3>Ele não expulsou primeiro.</h3><p>Primeiro tentou entender por que aquele espírito ainda estava ali.</p></div></div><figure class="cinematic-strip cinematic-strip-tavern reveal" data-panorama=""><img alt="Primeiro exorcismo de Seika em panorama dentro da taverna, com o pequeno espírito azul." loading="lazy" src="assets/web/wide-first-exorcism-full.avif"/><figcaption><span>Primeiro exorcismo</span> O espírito não precisava de violência. Precisava ser ouvido.</figcaption></figure></section>
<section class="absence scene-observer" data-chapter="ausencia" data-season="primavera" id="ausencia"><div aria-hidden="true" class="absence-bg"></div><div class="absence-copy reveal"><p class="chapter-kicker">VI · A primavera que não veio</p><h2>Ren não voltou.</h2><p>No começo podia ser atraso. Depois Seika começou a caminhar um pouco além do necessário quando procurava ervas na direção da estrada.</p></div><div aria-label="A espera de Seika" class="waiting-counter reveal"><div><strong>1</strong><span>semana</span><small>normal</small></div><div><strong>2</strong><span>semanas</span><small>ainda possível</small></div><div><strong>1</strong><span>mês</span><small>olhando a estrada</small></div><div><strong>fim</strong><span>da primavera</span><small>não mais que isso</small></div></div><div aria-label="As cartas enviadas por Seika" class="letters reveal"><article class="letter"><span class="letter-thread"></span><small>primeira carta</small><p>Brincadeiras. Notícias da vila. Uma pergunta simples: quando você chega?</p><i>sem resposta</i></article><article class="letter letter-second"><span class="letter-thread"></span><small>algumas semanas depois</small><p>O humor ainda estava ali. O fim da carta, não.</p><blockquote>“Me avise que está bem.”</blockquote><i>nada</i></article></div><div aria-label="Distância até a cidade de Ren" class="route-measure reveal"><span>vila</span><div aria-hidden="true" class="route-dashes"></div><strong>≈ duas semanas de viagem</strong><div aria-hidden="true" class="route-dashes"></div><span>casa de Ren</span></div></section>
<section class="chapter mantle scene-observer" data-chapter="manto" data-season="verao" id="manto"><div class="section-heading reveal"><p class="chapter-kicker">VIII · O manto</p><h2>Ele não saiu sozinho.<br/><em>A vila foi costurada nele.</em></h2></div><div class="layered-scene departure-layered" data-tilt-scene=""><div class="layered-back layered-full parallax-layer" data-depth="0.08"><img alt="A despedida de Seika no começo do verão, com Ami e a vila ao fundo." loading="lazy" src="assets/web/wide-departure-full.avif"/></div><div aria-hidden="true" class="golden-bloom"></div><div class="scene-caption reveal"><span class="memory-index">começo do verão · 23 anos</span><h3>“Você parece um pouco com o Ren.”</h3><p>“Nossa. Ficou tão ruim assim?”</p></div></div><div class="packed-home reveal"><h3>O que foi para a estrada</h3><div class="packed-grid"><span><b>Haru</b><small>ervas úteis</small></span><span><b>Mei</b><small>remédios, bandagens, provisões escondidas</small></span><span><b>Nao</b><small>comida adequada para a viagem</small></span><span><b>Kenta</b><small>conselhos úteis e preocupantes</small></span><span><b>Ami</b><small>o manto, os bolsos, os espaços para talismãs</small></span><span><b>Ren</b><small>uma silhueta que a roupa acabou evocando</small></span></div></div><figure class="reference-frame reveal"><img alt="Arte original da partida de Seika no começo do verão." loading="lazy" src="assets/web/wide-departure-full.avif"/><figcaption><small>registro original</small><strong>A partida</strong><span>Ele acreditava que voltaria em poucos meses.</span></figcaption></figure></section>
<section class="departure-cinematic scene-observer" data-chapter="partida" data-season="verao" id="partida"><div class="departure-sticky"><div aria-hidden="true" class="departure-pan" id="departurePan"><img alt="" loading="lazy" src="assets/web/wide-departure-full.avif"/></div><div class="departure-overlay"></div><div aria-live="off" class="departure-lines"><p data-departure-line="0">Não como aventureiro.</p><p data-departure-line="1">Não como herói.</p><p data-departure-line="2">Não como escolhido.</p><p class="departure-main" data-departure-line="3">Apenas como alguém indo procurar um amigo<br/>que deveria ter voltado para casa.</p></div></div></section>
<section class="promise scene-observer" data-chapter="promessa" data-season="inverno"><div aria-hidden="true" class="promise-ink"><img alt="" loading="lazy" src="assets/web/wide-adult-seika-full.avif"/></div><div aria-hidden="true" class="promise-wash"></div><div class="promise-copy reveal"><small>Antes de sair, prometeu:</small><blockquote>“Volto antes do inverno.”</blockquote><p>Não porque pretendesse ficar fora por toda a estação. Era apenas o limite: antes que o clima piorasse, antes que as estradas ficassem ruins, antes que voltar se tornasse difícil.</p><p class="promise-last">Naquele momento, Seika não via motivo algum para não acreditar.</p></div></section>
<section class="character-codex scene-observer" data-chapter="caderno" data-season="inverno" id="caderno"><div class="codex-portrait reveal"><img alt="Retrato de corpo inteiro de Seika adulto, com manto preto, branco, dourado e violeta, talismãs e bastão ritual." loading="lazy" src="assets/web/wide-adult-seika-full.avif"/><div aria-hidden="true" class="portrait-moon"></div></div><div class="codex-copy reveal"><p class="chapter-kicker">Caderno de viagem</p><h2>Quem é Seika?</h2><p class="codex-lede">Gentil sem ser ingênuo. Curioso sem ser acadêmico. Prestativo a ponto de frequentemente complicar os próprios planos.</p><div class="principles"><p>Se pode ajudar sem causar um mal maior, deve tentar.</p><p>Quem pede ajuda merece pelo menos ser ouvido.</p><p>Nem todo espírito é maligno.</p><p>Compreender não significa confiar.</p><p>Poder existe para proteger quem não consegue se proteger sozinho.</p><p>Casa continua sendo casa, mesmo quando ele está longe.</p></div></div><div class="roleplay-notes reveal"><article><span>Lucky</span><p>Amigos de infância ainda podem chamá-lo assim. Ele reclama mais do que realmente se incomoda.</p></article><article><span>Humor</span><p>Quando está preocupado, é comum uma piada chegar antes da admissão.</p></article><article><span>Ervas</span><p>Reconhece muitas pelo cheiro e pensa em Haru quando encontra uma rara.</p></article><article><span>Estrada</span><p>Ainda tem o péssimo hábito de se desviar do próprio caminho para ajudar alguém.</p></article><article><span>Espíritos</span><p>A primeira pergunta continua sendo “o que está acontecendo?”, não “como eu destruo isso?”.</p></article><article><span>Falha possível</span><p>Tem dificuldade em aceitar que alguém não pode ser salvo enquanto ainda existir alguma possibilidade de tentar.</p></article></div></section>
<section aria-labelledby="selos-titulo" class="unanswered scene-observer" data-season="inverno"><div class="unanswered-head reveal"><p class="chapter-kicker">Selos não respondidos</p><h2 id="selos-titulo">Algumas perguntas devem continuar abertas.</h2><p>Esta página não transforma símbolo visual em resposta canônica. O mistério de Seika continua sendo mistério.</p></div><details class="dm-vault reveal"><summary><span>⚿</span> Abrir notas do DM <small>spoilers e ganchos abertos</small></summary><div class="seal-grid"><article><b>01</b><h3>Lucky</h3><p>Coincidência, poder precoce, influência externa ou outra coisa?</p></article><article><b>02</b><h3>O ritual de Ami</h3><p>O que exatamente respondeu quando Seika tentou ajudar?</p></article><article><b>03</b><h3>Ren</h3><p>Ferido, desaparecido, preso, evitando a vila ou envolvido em algo maior?</p></article><article><b>04</b><h3>As cartas</h3><p>Chegaram, foram interceptadas ou simplesmente ficaram sem resposta?</p></article><article><b>05</b><h3>Vida, cura e espíritos</h3><p>Existe relação entre os poderes de Seika e essa afinidade?</p></article><article><b>06</b><h3>O inverno</h3><p>A promessa será cumprida?</p></article></div></details></section>
<section aria-labelledby="arquivo-titulo" class="visual-archive scene-observer" data-season="inverno" id="arquivo"><div class="archive-head reveal"><p class="chapter-kicker">Arquivo visual</p><h2 id="arquivo-titulo">Registros da mesma história.</h2><p>Panoramas usados na experiência. Toque em qualquer imagem para abrir em tela cheia.</p></div><div class="archive-grid" id="archiveGrid"><button class="archive-item wide reveal" data-lightbox="" type="button"><img alt="Lucky nas ruínas" loading="lazy" src="assets/web/wide-lucky-full.avif"/><span>Lucky nas ruínas</span></button><button class="archive-item wide reveal" data-lightbox="" type="button"><img alt="Ritual de Ami" loading="lazy" src="assets/web/wide-ami-ritual-full.avif"/><span>Ritual de Ami</span></button><button class="archive-item wide reveal" data-lightbox="" type="button"><img alt="Primeiro exorcismo" loading="lazy" src="assets/web/wide-first-exorcism-full.avif"/><span>Primeiro exorcismo</span></button><button class="archive-item wide reveal" data-lightbox="" type="button"><img alt="A partida" loading="lazy" src="assets/web/wide-departure-full.avif"/><span>A partida</span></button><button class="archive-item wide reveal" data-lightbox="" type="button"><img alt="Seika adulto" loading="lazy" src="assets/web/wide-adult-seika-full.avif"/><span>Seika adulto</span></button><button class="archive-item wide reveal" data-lightbox="" type="button"><img alt="Lua, tinta e espírito" loading="lazy" src="assets/web/wide-ink-moon.avif"/><span>Lua, tinta e espírito</span></button></div></section>
<footer class="finale"><div aria-hidden="true" class="finale-mark">◐</div><p>SEIKA</p><strong>Antes do Inverno</strong><small>Uma história sobre cuidado, casa e a estrada que começa quando alguém não volta.</small><a href="#topo">voltar ao começo ↑</a></footer>
</main>
<dialog aria-label="Visualizador de imagem" class="lightbox" id="lightbox"><button aria-label="Fechar imagem" class="lightbox-close" id="lightboxClose" type="button">×</button><img alt="" id="lightboxImage" src=""/><p id="lightboxCaption"></p></dialog>
<noscript><style>.reveal{opacity:1!important;transform:none!important}.parallax-layer{transform:none!important}</style></noscript>
<script defer src="script.js"></script>
</body>
</html>`;

export function GET() {
  return new Response(BODY, {
    headers: {
      "Content-Type": "text/html; charset=utf-8",
      "Cache-Control": "public, max-age=300, s-maxage=3600, stale-while-revalidate=86400",
    },
  });
}
