import { beforeEach, describe, expect, it, vi } from "vitest";
const mocks=vi.hoisted(()=>({currentAccess:vi.fn(),readNavigationCampaigns:vi.fn()}));
vi.mock("@/features/auth/server",()=>({currentAccess:mocks.currentAccess}));
vi.mock("@/features/campaigns/navigation",()=>({readNavigationCampaigns:mocks.readNavigationCampaigns}));
import { GET } from "./route";
beforeEach(()=>{vi.clearAllMocks();mocks.currentAccess.mockResolvedValue({state:"anonymous",context:null,identity:null});mocks.readNavigationCampaigns.mockResolvedValue({mode:"first_class",campaigns:[]});});
describe("GET /api/auth/me",()=>{
	it("keeps anonymous navigation minimal and private",async()=>{const r=await GET();expect(await r.json()).toEqual({state:"anonymous",scope:{type:"project",id:"tda"},campaignsState:"none",campaigns:[]});expect(mocks.readNavigationCampaigns).not.toHaveBeenCalled();expect(r.headers.get("cache-control")).toBe("private, no-store");});
	it("returns sanitized per-campaign projection",async()=>{mocks.currentAccess.mockResolvedValueOnce({state:"authenticated_linked",identity:{displayName:"Renan",avatarUrl:null},context:{authUserId:"secret-user",profileId:"secret-profile",grants:[]}});mocks.readNavigationCampaigns.mockResolvedValueOnce({mode:"first_class",campaigns:[{technicalSlug:"yuhara-main",routeKey:"cronicas-da-mesa",name:"Crônicas da Mesa",lifecycle:"active",capabilities:["campaign.local.process"]}]});const body=await (await GET()).json();expect(body).toEqual({state:"authenticated_linked",scope:{type:"project",id:"tda"},identity:{displayName:"Renan",avatarUrl:null},capabilities:[],campaignsState:"first_class",campaigns:[{technicalSlug:"yuhara-main",routeKey:"cronicas-da-mesa",name:"Crônicas da Mesa",lifecycle:"active",capabilities:["campaign.local.process"]}]});expect(JSON.stringify(body)).not.toContain("secret-");});
	it("keeps authenticated unlinked empty instead of unavailable",async()=>{mocks.currentAccess.mockResolvedValueOnce({state:"authenticated_unlinked",identity:{displayName:"Corujinha",avatarUrl:null},context:{authUserId:"x",profileId:null,grants:[]}});expect(await (await GET()).json()).toEqual({state:"authenticated_unlinked",scope:{type:"project",id:"tda"},identity:{displayName:"Corujinha",avatarUrl:null},capabilities:[],campaignsState:"first_class",campaigns:[]});});
	it("fails campaign discovery closed",async()=>{mocks.currentAccess.mockResolvedValueOnce({state:"authenticated_linked",identity:{displayName:"Pessoa",avatarUrl:null},context:{authUserId:"x",profileId:"p",grants:[]}});mocks.readNavigationCampaigns.mockResolvedValueOnce({mode:"unavailable",campaigns:[]});const r=await GET();expect(r.status).toBe(200);expect(await r.json()).toMatchObject({state:"authenticated_linked",campaignsState:"unavailable",campaigns:[]});});
	it("returns 503 for unavailable access",async()=>{mocks.currentAccess.mockResolvedValueOnce({state:"unavailable",context:null,identity:null});const r=await GET();expect(r.status).toBe(503);expect(await r.json()).toEqual({state:"unavailable",scope:{type:"project",id:"tda"},campaignsState:"unavailable",campaigns:[]});});
});
