-- TDA domain alignment.
-- Backward-compatible with the legacy dnd-scribe application while it remains operational.

begin;

-- TDA is the canonical project scope for the reboot. Keep the legacy scope assignments
-- during the transition because dnd-scribe still asks for scope_id = 'dnd-scribe'.
insert into public.role_assignments (
  profile_id,
  role_id,
  scope_type,
  scope_id,
  status,
  starts_at,
  ends_at,
  assigned_by,
  revoked_by,
  reason,
  metadata
)
select
  legacy.profile_id,
  legacy.role_id,
  legacy.scope_type,
  'tda',
  legacy.status,
  legacy.starts_at,
  legacy.ends_at,
  legacy.assigned_by,
  legacy.revoked_by,
  coalesce(legacy.reason, 'TDA canonical project scope created from legacy compatibility assignment'),
  coalesce(legacy.metadata, '{}'::jsonb) || jsonb_build_object(
    'canonicalProjectScope', 'tda',
    'compatibilitySourceScope', 'dnd-scribe'
  )
from public.role_assignments legacy
where legacy.scope_type = 'project'
  and legacy.scope_id = 'dnd-scribe'
  and not exists (
    select 1
    from public.role_assignments current_scope
    where current_scope.profile_id = legacy.profile_id
      and current_scope.role_id = legacy.role_id
      and current_scope.scope_type = 'project'
      and current_scope.scope_id = 'tda'
      and current_scope.status = legacy.status
      and current_scope.ends_at is not distinct from legacy.ends_at
  );

-- entities is the canonical registry for narrative/world objects. profile_characters
-- becomes the association between a human profile and a PC entity.
alter table public.entities
  add column if not exists aliases text[] not null default '{}'::text[];

create unique index if not exists entities_campaign_slug_unique
  on public.entities(campaign_id, slug)
  where slug is not null;

alter table public.profile_characters
  add column if not exists entity_id uuid;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'profile_characters_entity_id_fkey'
      and conrelid = 'public.profile_characters'::regclass
  ) then
    alter table public.profile_characters
      add constraint profile_characters_entity_id_fkey
      foreign key (entity_id) references public.entities(id) on delete restrict;
  end if;
end $$;

create index if not exists profile_characters_entity_id_idx
  on public.profile_characters(entity_id);

-- A participant is a per-session appearance. Linking it to the canonical PC entity
-- avoids relying on display-name matching in future timeline/search features.
alter table public.participants
  add column if not exists character_entity_id uuid;

do $$
begin
  if not exists (
    select 1 from pg_constraint
    where conname = 'participants_character_entity_id_fkey'
      and conrelid = 'public.participants'::regclass
  ) then
    alter table public.participants
      add constraint participants_character_entity_id_fkey
      foreign key (character_entity_id) references public.entities(id) on delete restrict;
  end if;
end $$;

create index if not exists participants_character_entity_id_idx
  on public.participants(character_entity_id);

-- Backfill existing player characters. The current production names are ASCII-safe;
-- future entity slugs must be generated by the application/domain layer.
insert into public.entities (
  campaign_id,
  name,
  slug,
  entity_type,
  status,
  visibility,
  summary,
  aliases
)
select
  pc.campaign_id,
  pc.character_name,
  nullif(trim(both '-' from lower(regexp_replace(pc.character_name, '[^A-Za-z0-9]+', '-', 'g'))), ''),
  'pc',
  case when pc.status = 'archived' then 'archived' else 'active' end,
  'private_players',
  null,
  coalesce(pc.aliases, '{}'::text[])
from public.profile_characters pc
where pc.status <> 'npc'
on conflict (campaign_id, name) do nothing;

update public.profile_characters pc
set entity_id = entity.id
from public.entities entity
where pc.entity_id is null
  and entity.campaign_id = pc.campaign_id
  and lower(entity.name) = lower(pc.character_name)
  and entity.entity_type = 'pc';

update public.participants participant
set character_entity_id = pc.entity_id
from public.sessions session,
     public.profile_characters pc
where participant.character_entity_id is null
  and participant.session_id = session.id
  and pc.campaign_id = session.campaign_id
  and pc.entity_id is not null
  and participant.profile_id = pc.profile_id
  and lower(coalesce(participant.character_name, '')) = lower(pc.character_name);

comment on table public.entities is
  'Canonical narrative entity registry for PCs, NPCs, locations, items, organizations, factions, arcs, concepts, songs and quests.';
comment on column public.entities.aliases is
  'Known alternate names used for entity resolution. Canonical name remains entities.name.';
comment on column public.profile_characters.entity_id is
  'Canonical PC entity controlled/represented by this profile-character association.';
comment on column public.participants.character_entity_id is
  'Canonical character entity represented by this participant in one session when known.';

commit;
